apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-002-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-002-hello
  template:
    metadata:
      labels:
        app: devops-002-hello
    spec:
      containers:
      - name: devops-002-hello
        image: erdincekzts/devops_gradle_hello:V001
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
