apiVersion: v1
kind: Pod
metadata:
  name: devops-002-hello
  labels:
    app.kubernetes.io/name: devops-002-hello
    my-type: backend
    my-module: module1
    my-project-name: devops-002
spec:
  containers:
    - name: devops-002-hello
      image: erdincekzts/devops_gradle_hello:V001
      resources:
        limits:
          memory: "200Mi"
          cpu: "500m"
      ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Pod
metadata:
  name: devops-002-hello
  labels:
    app.kubernetes.io/name: devops-002-hello
    my-type: frontend
    my-module: module2
    my-project-name: devops-002
spec:
  containers:
    - name: devops-002-hello
      image: erdincekzts/devops_gradle_hello:V001
      resources:
        limits:
          memory: "300Mi"
          cpu: "500m"
      ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Pod
metadata:
  name: devops-002-hello
  labels:
    app.kubernetes.io/name: devops-002-hello
    my-type: mobile
    my-module: module3
    my-project-name: devops-002
spec:
  containers:
    - name: devops-002-hello
      image: erdincekzts/devops_gradle_hello:V001
      resources:
        limits:
          memory: "150Mi"
          cpu: "500m"
      ports:
        - containerPort: 9093