apiVersion: v1
kind: Service
metadata:
  name: devops-002-hello
spec:
  selector:
    app: devops-002-hello
  ports:
  - port: 9090 # Service dinleyeceği Port
    targetPort: 8080 # Pod içindeki Container'ın Portu
  type: ClusterIP # Service tipi (ClusterIP, NodePort, LoadBalancer)     
  